name: grpc_demo
description: A grpc demo Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  path: ^1.8.0
  grpc: ^3.0.2
  protobuf: ^2.0.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true